### ISSUE TITLE
In outlets option delete option is not working

### ISSUE THREAD

**Issue by asmafareed** [fareed543/Point-of-Sale-Web-Application#3]
![image](https://user-images.githubusercontent.com/22454620/35038191-0872201c-fba0-11e7-8ee3-00ec9cb7371c.png)

to erase the unwanted information delete key is a must. but here it is not working. here the information is not erased but here instead of not erasing the information it is shown as it is deleted successfully

**Comment by abidali70722** [comment]
Outlet delete issue fixed
