### ISSUE TITLE
In product category delete option is not working

### ISSUE THREAD

**Issue by asmafareed** [fareed543/Point-of-Sale-Web-Application#8]
![image](https://user-images.githubusercontent.com/22454620/35042772-e8bd44ee-fbaf-11e7-83ef-6c70323f4bdb.png)

in the product category, delete option is not working. so unnecessary products removal is a tough task so changes are needed to get a better result

**Comment by abidali70722** [comment]
Product category Delete. I have added funtion to constant model.... I have uri segment of CI to delete records
